export const iconMap = {
  // Search & UI
  search: 'solar:magnifer-linear',
  check: 'solar:check-square-linear',
  checkCircle: 'solar:check-circle-linear',
  close: 'solar:close-circle-linear',
  info: 'solar:info-circle-linear',
  alertTriangle: 'solar:danger-triangle-linear',
  alertCircle: 'solar:danger-circle-linear',
  x: 'solar:close-circle-linear',
  xCircle: 'solar:close-circle-linear',
  sun: 'solar:sun-2-linear',
  moon: 'solar:moon-linear',
  calendar: 'solar:calendar-date-linear',
  language: 'solar:earth-linear',

  // Arrows & Chevrons
  chevronDown: 'solar:alt-arrow-down-linear',
  chevronUp: 'solar:alt-arrow-up-linear',
  chevronLeft: 'solar:alt-arrow-left-linear',
  chevronRight: 'solar:alt-arrow-right-linear',
  arrowLeft: 'solar:alt-arrow-left-linear',
  arrowRight: 'solar:alt-arrow-right-linear',

  // Documents & Files
  fileText: 'solar:file-text-linear',
  fileCode: 'solar:code-file-linear',
  document: 'solar:document-linear',
  filePlus: 'solar:document-add-linear',
  scroll: 'solar:notebook-minimalistic-linear',
  notebook: 'solar:notebook-linear',
  clipboard: 'solar:clipboard-text-linear',
  clipboardList: 'solar:clipboard-list-linear',

  // Folders
  folder: 'solar:folder-linear',
  folderOpen: 'solar:folder-open-linear',
  folderPlus: 'solar:add-folder-linear',
  folderTree: 'solar:folder-path-connect-linear',

  // Navigation
  home: 'solar:home-2-linear',
  compass: 'solar:compass-linear',
  map: 'solar:map-linear',
  mapPin: 'solar:map-point-linear',
  bookmark: 'solar:bookmark-linear',
  menu: 'solar:hamburger-menu-linear',
  panelLeft: 'solar:sidebar-minimalistic-linear',
  layoutDashboard: 'solar:widget-5-linear',
  layoutGrid: 'solar:widget-linear',
  layoutList: 'solar:list-linear',

  // Settings & Config
  settings: 'solar:settings-linear',
  wrench: 'solar:settings-minimalistic-linear',
  sliders: 'solar:tuning-2-linear',
  slidersHorizontal: 'solar:tuning-linear',

  // Actions
  bolt: 'solar:bolt-linear',
  zap: 'solar:bolt-linear',
  rocket: 'solar:rocket-linear',
  play: 'solar:play-linear',
  download: 'solar:download-linear',
  upload: 'solar:upload-linear',
  refreshCw: 'solar:refresh-linear',
  refresh: 'solar:refresh-linear',
  trash: 'solar:trash-bin-trash-linear',
  pencil: 'solar:pen-linear',
  plus: 'solar:add-circle-linear',
  copy: 'solar:copy-linear',
  sparkles: 'solar:stars-linear',
  lightbulb: 'solar:lightbulb-linear',

  // Electronic & Devices
  smartphone: 'solar:smartphone-linear',
  smartphone2: 'solar:smartphone-2-linear',
  smartphoneRotate: 'solar:smartphone-rotate-2-linear',
  smartphoneUpdate: 'solar:smartphone-update-linear',
  smartphoneVibration: 'solar:smartphone-vibration-linear',
  tablet: 'solar:tablet-linear',
  monitor: 'solar:monitor-linear',
  monitorCamera: 'solar:monitor-camera-linear',
  monitorSmartphone: 'solar:monitor-smartphone-linear',
  laptop: 'solar:laptop-linear',
  laptop2: 'solar:laptop-2-linear',
  laptopMinimalistic: 'solar:laptop-minimalistic-linear',
  tv: 'solar:tv-linear',
  watch: 'solar:watch-round-linear',
  display: 'solar:display-linear',
  devices: 'solar:devices-linear',
  windowFrame: 'solar:window-frame-linear',

  // Audio & Media Devices
  airbuds: 'solar:airbuds-linear',
  airbudsCase: 'solar:airbuds-case-linear',
  airbudsCharge: 'solar:airbuds-charge-linear',
  headphones: 'solar:headphones-round-linear',
  headphonesSound: 'solar:headphones-round-sound-linear',
  headphonesSquare: 'solar:headphones-square-linear',
  boombox: 'solar:boombox-linear',
  smartSpeaker: 'solar:smart-speaker-linear',
  turntable: 'solar:turntable-linear',
  cassette: 'solar:cassette-linear',

  // Input & Peripherals
  keyboard: 'solar:keyboard-linear',
  mouse: 'solar:mouse-linear',
  printer: 'solar:printer-linear',
  printerMinimalistic: 'solar:printer-minimalistic-linear',
  projector: 'solar:projector-linear',

  // Gaming
  gamepad: 'solar:gamepad-linear',
  gamepadMinimalistic: 'solar:gamepad-minimalistic-linear',
  gamepadOld: 'solar:gamepad-old-linear',
  gameboy: 'solar:gameboy-linear',

  // Storage & Cards
  diskette: 'solar:diskette-linear',
  flashDrive: 'solar:flash-drive-linear',
  sdCard: 'solar:sd-card-linear',
  simCard: 'solar:sim-card-linear',
  ssdRound: 'solar:ssd-round-linear',
  ssdSquare: 'solar:ssd-square-linear',
  cloudStorage: 'solar:cloud-storage-linear',

  // Power & Connectivity
  socket: 'solar:socket-linear',
  lightning: 'solar:lightning-linear',
  wirelessCharge: 'solar:wireless-charge-linear',
  weigher: 'solar:weigher-linear',
  telescope: 'solar:telescope-linear',

  // Map & Navigation arrows
  mapArrowDown: 'solar:map-arrow-down-linear',
  mapArrowUp: 'solar:map-arrow-up-linear',

  // Sliders
  sliderVertical: 'solar:slider-vertical-linear',
  sliderHorizontal: 'solar:slider-horizontal-linear',

  // Magic & Effects
  magicStick: 'solar:magic-stick-3-linear',

  // Operating Systems & Brands
  apple: 'solar:iphone-linear',
  android: 'solar:smartphone-linear',
  windows: 'solar:window-frame-linear',
  chrome: 'solar:magnifer-linear',
  github: 'solar:code-square-linear',
  gitlab: 'solar:code-square-linear',
  figma: 'solar:figma-linear',
  slack: 'solar:chat-square-linear',
  trello: 'solar:widget-2-linear',
  twitter: 'solar:chat-round-linear',
  youtube: 'solar:play-linear',
  linkedin: 'solar:user-id-linear',
  facebook: 'solar:chat-round-linear',
  instagram: 'solar:camera-linear',
  dribbble: 'solar:basketball-linear',

  // Infrastructure
  server: 'solar:server-linear',
  cloud: 'solar:cloud-linear',
  database: 'solar:database-linear',
  cpu: 'solar:cpu-linear',
  hardDrive: 'solar:server-square-linear',
  wifi: 'solar:wi-fi-router-linear',
  bluetooth: 'solar:bluetooth-wave-linear',

  // Development & API
  code: 'solar:code-linear',
  terminal: 'solar:command-linear',
  gitBranch: 'solar:share-linear',
  gitCommit: 'solar:record-circle-linear',
  gitMerge: 'solar:share-linear',
  gitPullRequest: 'solar:share-linear',
  webhook: 'solar:link-round-angle-linear',
  api: 'solar:programming-linear',
  binary: 'solar:code-linear',
  bug: 'solar:bug-linear',

  // Integrations & Plugins
  plug: 'solar:plug-circle-linear',
  puzzle: 'solar:widget-add-linear',
  package: 'solar:box-linear',
  layers: 'solar:layers-linear',
  box: 'solar:box-linear',
  blocks: 'solar:widget-linear',
  component: 'solar:widget-2-linear',

  // Security
  shield: 'solar:shield-linear',
  shieldCheck: 'solar:shield-check-linear',
  shieldAlert: 'solar:shield-warning-linear',
  lock: 'solar:lock-linear',
  lockOpen: 'solar:lock-unlocked-linear',
  key: 'solar:key-linear',
  fingerprint: 'solar:shield-keyhole-linear',
  eye: 'solar:eye-linear',
  eyeOff: 'solar:eye-closed-linear',

  // Documentation
  book: 'solar:book-2-linear',
  bookOpen: 'solar:book-linear',
  bookMarked: 'solar:book-bookmark-linear',

  // Users & Organization
  user: 'solar:user-linear',
  userCheck: 'solar:user-check-linear',
  userPlus: 'solar:user-plus-linear',
  users: 'solar:users-group-two-rounded-linear',
  building: 'solar:buildings-linear',
  briefcase: 'solar:case-linear',

  // Communication
  bell: 'solar:bell-linear',
  mail: 'solar:letter-linear',
  messageSquare: 'solar:chat-square-linear',
  messageCircle: 'solar:chat-round-linear',
  phone: 'solar:phone-linear',
  video: 'solar:camera-linear',
  helpCircle: 'solar:question-circle-linear',

  // Analytics & Data
  barChart: 'solar:chart-linear',
  lineChart: 'solar:graph-up-linear',
  pieChart: 'solar:pie-chart-2-linear',
  trendingUp: 'solar:graph-up-linear',
  activity: 'solar:health-linear',

  // Misc
  star: 'solar:star-linear',
  heart: 'solar:heart-linear',
  flag: 'solar:flag-linear',
  tag: 'solar:tag-linear',
  globe: 'solar:earth-linear',
  globe2: 'solar:earth-linear',
  link: 'solar:link-linear',
  link2: 'solar:link-linear',
  externalLink: 'solar:link-round-angle-linear',
  image: 'solar:gallery-minimalistic-linear',
  bot: 'solar:chat-round-dots-linear',
  palette: 'solar:palette-linear',
  history: 'solar:clock-circle-linear',

  // Editor & UI specific
  panelTopOpen: 'solar:window-frame-linear',
  listTree: 'solar:folder-path-connect-linear',
  listOrdered: 'solar:list-linear',
  penLine: 'solar:pen-linear',
  gripVertical: 'solar:menu-dots-linear',
  moreVertical: 'solar:menu-dots-square-linear',
  tableProperties: 'solar:checklist-minimalistic-linear',
  square: 'solar:stop-linear',

  // Kebab-case mappings (synced from CMS)
  'smartphone': 'solar:smartphone-linear',
  'smartphone-2': 'solar:smartphone-2-linear',
  'smartphone-rotate': 'solar:smartphone-rotate-2-linear',
  'smartphone-update': 'solar:smartphone-update-linear',
  'smartphone-vibration': 'solar:smartphone-vibration-linear',
  'tablet-smartphone': 'solar:tablet-linear',
  'tablet': 'solar:tablet-linear',
  'monitor': 'solar:monitor-linear',
  'monitor-camera': 'solar:monitor-camera-linear',
  'monitor-smartphone': 'solar:monitor-smartphone-linear',
  'laptop': 'solar:laptop-linear',
  'laptop-2': 'solar:laptop-2-linear',
  'laptop-minimalistic': 'solar:laptop-minimalistic-linear',
  'tv': 'solar:tv-linear',
  'watch': 'solar:watch-round-linear',
  'display': 'solar:display-linear',
  'devices': 'solar:devices-linear',
  'airbuds': 'solar:airbuds-linear',
  'airbuds-case': 'solar:airbuds-case-linear',
  'airbuds-charge': 'solar:airbuds-charge-linear',
  'headphones': 'solar:headphones-round-linear',
  'headphones-sound': 'solar:headphones-round-sound-linear',
  'headphones-square': 'solar:headphones-square-linear',
  'boombox': 'solar:boombox-linear',
  'smart-speaker': 'solar:smart-speaker-linear',
  'turntable': 'solar:turntable-linear',
  'cassette': 'solar:cassette-linear',
  'keyboard': 'solar:keyboard-linear',
  'mouse': 'solar:mouse-linear',
  'printer': 'solar:printer-linear',
  'printer-minimalistic': 'solar:printer-minimalistic-linear',
  'projector': 'solar:projector-linear',
  'gamepad': 'solar:gamepad-linear',
  'gamepad-minimalistic': 'solar:gamepad-minimalistic-linear',
  'gamepad-old': 'solar:gamepad-old-linear',
  'gameboy': 'solar:gameboy-linear',
  'diskette': 'solar:diskette-linear',
  'flash-drive': 'solar:flash-drive-linear',
  'sd-card': 'solar:sd-card-linear',
  'sim-card': 'solar:sim-card-linear',
  'ssd-round': 'solar:ssd-round-linear',
  'ssd-square': 'solar:ssd-square-linear',
  'cloud-storage': 'solar:cloud-storage-linear',
  'socket': 'solar:socket-linear',
  'lightning': 'solar:lightning-linear',
  'wireless-charge': 'solar:wireless-charge-linear',
  'weigher': 'solar:weigher-linear',
  'telescope': 'solar:telescope-linear',
  'iphone': 'solar:smartphone-linear',
  'ipad': 'solar:tablet-linear',
  'hard-drive': 'solar:server-square-linear',
  'memory-stick': 'solar:cpu-linear',
  'circuit-board': 'solar:cpu-linear',
  'code-2': 'solar:code-linear',
  'terminal-square': 'solar:command-linear',
  'git-branch': 'solar:share-linear',
  'git-commit': 'solar:record-circle-linear',
  'git-merge': 'solar:share-linear',
  'git-pull-request': 'solar:share-linear',
  'bug-off': 'solar:bug-linear',
  'test-tube': 'solar:test-tube-linear',
  'flask-conical': 'solar:test-tube-linear',
  'plug-2': 'solar:plug-circle-linear',
  'package-open': 'solar:box-linear',
  'layers-2': 'solar:layers-linear',
  'shield-check': 'solar:shield-check-linear',
  'shield-alert': 'solar:shield-warning-linear',
  'shield-off': 'solar:shield-cross-linear',
  'lock-open': 'solar:lock-unlocked-linear',
  'key-round': 'solar:key-linear',
  'scan-face': 'solar:face-scan-circle-linear',
  'eye-off': 'solar:eye-closed-linear',
  'book-2': 'solar:book-2-linear',
  'book-marked': 'solar:book-bookmark-linear',
  'file-json': 'solar:code-file-linear',
  'clipboard-list': 'solar:clipboard-list-linear',
  'folder-open': 'solar:folder-open-linear',
  'folder-tree': 'solar:folder-path-connect-linear',
  'panel-left': 'solar:sidebar-minimalistic-linear',
  'layout-dashboard': 'solar:widget-5-linear',
  'layout-grid': 'solar:widget-linear',
  'layout-list': 'solar:list-linear',
  'map-arrow-down': 'solar:map-arrow-down-linear',
  'map-arrow-up': 'solar:map-arrow-up-linear',
  'slider-vertical': 'solar:slider-vertical-linear',
  'slider-horizontal': 'solar:slider-horizontal-linear',
  'magic-stick': 'solar:magic-stick-3-linear',
  'settings-2': 'solar:settings-linear',
  'cog': 'solar:settings-linear',
  'columns-3-cog': 'solar:settings-linear',
  'sliders-horizontal': 'solar:tuning-linear',
  'toggle-left': 'solar:slider-horizontal-linear',
  'toggle-right': 'solar:slider-vertical-linear',
  'zap-off': 'solar:bolt-linear',
  'refresh-cw': 'solar:refresh-linear',
  'trash-2': 'solar:trash-bin-trash-linear',
  'user-check': 'solar:user-check-linear',
  'user-plus': 'solar:user-plus-linear',
  'building-2': 'solar:buildings-2-linear',
  'id-card': 'solar:card-linear',
  'bell-ring': 'solar:bell-bing-linear',
  'message-square': 'solar:chat-square-linear',
  'message-circle': 'solar:chat-round-linear',
  'help-circle': 'solar:question-circle-linear',
  'bar-chart': 'solar:chart-linear',
  'bar-chart-2': 'solar:chart-2-linear',
  'bar-chart-3': 'solar:chart-linear',
  'line-chart': 'solar:graph-up-linear',
  'pie-chart': 'solar:pie-chart-2-linear',
  'trending-up': 'solar:graph-up-linear',
  'trending-down': 'solar:graph-down-linear',
  'globe-2': 'solar:earth-linear',
  'link-2': 'solar:link-linear',
  'external-link': 'solar:link-round-angle-linear',
  'check-circle': 'solar:check-circle-linear',
  'check-circle-2': 'solar:check-circle-linear',
  'x-circle': 'solar:close-circle-linear',
  'alert-triangle': 'solar:danger-triangle-linear',
  'alert-circle': 'solar:danger-circle-linear',
  'loader-2': 'solar:restart-linear',
  'file-plus': 'solar:document-add-linear',
  'folder-plus': 'solar:add-folder-linear',
  'list-ordered': 'solar:list-linear',
  'list-tree': 'solar:folder-path-connect-linear',
  'pen-line': 'solar:pen-linear',
  'grip-vertical': 'solar:menu-dots-linear',
  'chevron-down': 'solar:alt-arrow-down-linear',
  'chevron-left': 'solar:alt-arrow-left-linear',
  'chevron-right': 'solar:alt-arrow-right-linear',
  'chevron-up': 'solar:alt-arrow-up-linear',
  'arrow-left': 'solar:alt-arrow-left-linear',
  'arrow-right': 'solar:alt-arrow-right-linear',
  'arrow-up': 'solar:alt-arrow-up-linear',
  'arrow-down': 'solar:alt-arrow-down-linear',
  'panel-top-open': 'solar:window-frame-linear',
  'heading-1': 'solar:text-field-linear',
  'heading-2': 'solar:text-field-linear',
  'heading-3': 'solar:text-field-linear',
  'list-check': 'solar:check-square-linear',
  'more-vertical': 'solar:menu-dots-square-linear',
  'more-horizontal': 'solar:menu-dots-linear',

  // Extended icons (synced from CMS icon picker)
} as const;

export type IconName = keyof typeof iconMap;
