export const iconMap = {
  search: 'solar:magnifer-linear',
  check: 'solar:check-square-linear',
  close: 'solar:close-circle-linear',
  info: 'solar:info-circle-linear',
  sun: 'solar:sun-2-linear',
  moon: 'solar:moon-linear',
  language: 'solar:earth-linear',
  chevronDown: 'solar:alt-arrow-down-linear',
  arrowLeft: 'solar:alt-arrow-left-linear',
  arrowRight: 'solar:alt-arrow-right-linear',
  fileText: 'solar:file-text-linear',
  document: 'solar:document-linear',
  folder: 'solar:folder-linear',
  folderOpen: 'solar:folder-open-linear',
  bolt: 'solar:bolt-linear',
  code: 'solar:code-linear',
  book: 'solar:book-2-linear',
  link: 'solar:link-linear',
  github: 'solar:link-linear',
  play: 'solar:play-linear',
  download: 'solar:download-linear',
  home: 'solar:home-2-linear',
  settings: 'solar:settings-linear',
  smartphone: 'solar:smartphone-linear',
  windowFrame: 'solar:window-frame-linear',
  refresh: 'solar:refresh-linear',
  lock: 'solar:lock-linear',
  menu: 'solar:hamburger-menu-linear',
  externalLink: 'solar:link-round-angle-linear',
  sparkles: 'solar:stars-linear'
} as const;

export type IconName = keyof typeof iconMap;
